apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system
resources:
- namespace.yaml
- istio-generated.yaml
- istio-gateway.yaml

patchesStrategicMerge:
  - ingressgateway-nlb-patch.yaml
