apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-jrr
resources:
- namespace.yaml
- svc.yaml
- istio-vs.yaml
- deployment.yaml

images:
- name: 676206941382.dkr.ecr.eu-west-1.amazonaws.com/app-jrr
  newName: 676206941382.dkr.ecr.eu-west-1.amazonaws.com/app-jrr
  newTag: 32e3e6e

configMapGenerator:
- literals:
  - APP_VERSION=32e3e6e
  name: app-version
