apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-jrr
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mandevnull/app-jrr.git
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mandevnull/app-jrr.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      spec:
        syncPolicy:
          automated:
            prune: false
            selfHeal: false


